### 同步组织架构
POST {{ host }}/api/v1/addressbook/sync
Content-Type: application/json

{}

### 更新租户信息
POST {{ host }}/api/v1/config/talent
Content-Type: application/json

{
  "corpId": "ww48fb21eab5cc8802",
  "agentId": "1000005",
  "addressBookSecret": "WiiJ3xygp_6dbL0ZbxFjtv4bDCUtLBGdRIEfKWblJYY",
  "appSecret": "5CJPjplEV9CWnF7J8tOmE4Toxy8xaTJkxKMV7kdqXqo",
  "externalContactSecret": "abcd",
  "addressBookCallbackToken": "B61HCDBO4N",
  "addressBookCallbackAesEncodingKey": "IivlYoyxpK8ErIQzokaV1DlXanTIpndSdL2DxPeZOzR"
}

### 通讯录变更回调
POST {{ host }}/callback/addressbook
Content-Type: text/xml

###
GET http://localhost:9090/a/b/c?a=1
Content-Type: application/json

###
POST http://localhost:8080/callback/addressbook?msg_signature=827d01b673f7ae109bea6cd713e5ce0c1c66ae40&timestamp=1654612061&nonce=1653862028
Content-Type: text/xml

<xml><ToUserName><![CDATA[ww48fb21eab5cc8802]]></ToUserName><Encrypt><![CDATA[zDJ3vIq9Rg6Sz7k3/wg6osjwapw1/U9kgJ9OtWdrJ/6BxaXTDvg671hR6i1VdpiSLIkryLcruhDgf74ZOBkwTNYBnWXMNqSTTF7eX0F70gh7bPBK4A5GamQFS5dIeOzDLygmz1xeHXMHJGZdBX+21x3U7u29KmtFOcmd5cq5yotl4mDjST4t5EhoxN2Ic06sLGu6jra/PAcIXyJ78/H7hzDpT91tD1IYvdnfpeZM0K9/ehzqtREzg9jvrENA+bbKbxZ+DhMFwYXHNDnjfkCt9NHs0xR9e/8y1UXGFVd7YkcbSueiLXgPA8ZKvvO5wPcE/J53OzfbY8yO5zXjaBs1gtp7sD0kmIKHqUxCAdm7zfuoEf1RqclAMB8akpBA5rTb5WCMbszToRkS9UoN3b5LwyCKyFfXzPrB3IY5DbS0XEvQt5cwy5gnBzEtTcP+HdcaJuSyBIThhxU4WQF0od9WRPm2iFmB0c39rH7k02syaNX4U7R9yQmkCKfMO0YhV3+09919JZxuv5zhxzSrr7sP+oMSTcpbUrEUqHybeWxW3qY=]]></Encrypt><AgentID><![CDATA[]]></AgentID></xml>


###
# curl 'http://localhost:8080/api/v1/auth/login'
#  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"'
#  -H 'think-lang: zh-cn'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
#  -H 'Content-Type: application/json'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Referer: http://localhost:1818/'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"username":"admin","password":"admin","captcha":"","keep":false,"loading":true,"captcha_id":"2734d60d-4e01-4ce1-a89b-10dbfdd9243a"}'
#  --compressed
OPTIONS http://localhost:8080/api/v1/auth/login
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
think-lang: zh-cn
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Referer: http://localhost:1818/
sec-ch-ua-platform: "Windows"
Content-Type: application/json

###

# curl 'http://localhost:8080/api/v1/auth/login'
#  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"'
#  -H 'think-lang: zh-cn'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
#  -H 'Content-Type: application/json'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Referer: http://localhost:1818/'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"username":"admin","password":"admin","captcha":"","keep":false,"loading":true,"captcha_id":"22fd97bc-4569-4009-8f9b-418cd39a6495"}'
#  --compressed
POST http://localhost:8080/api/v1/auth/login
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
think-lang: zh-cn
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Referer: http://localhost:1818/
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "captcha": "",
  "keep": false,
  "loading": true,
  "captcha_id": "22fd97bc-4569-4009-8f9b-418cd39a6495"
}

###

POST http://localhost:8080/api/v1/customer/syncall
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
think-lang: zh-cn
sec-ch-ua-mobile: ?0
Authorization: 36a58459-db8e-4ea6-8ebb-63baa70513f8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Referer: http://localhost:1818/
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{}

###

